version: '3.8'

services:
  db:
    image: postgres:15.2
    container_name: postgresql
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - ".env"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg_admin
    restart: always
    ports:
      - '127.0.0.1:5050:80'
    env_file:
      - ".env"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgdata:
  redis_data:
  redisinsight_data:
  pgadmin_data:
